name: React Native Expo CI with Maestro (Android)

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: macos-latest # macOS is required for running Android Emulators

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change to App Directory
        run: cd my-app # Ensure we're inside the correct folder

      - name: Install Expo CLI
        run: npm install -g expo-cli
        working-directory: my-app # Set working directory

      - name: Install Dependencies
        run: npm install
        working-directory: my-app

      - name: Start Android Emulator (Pixel 7, API 35)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          profile: pixel_7
          disable-animations: true
          script: echo "Android Emulator started!"

      - name: Print Emulator Details
        run: adb devices -l

      - name: Build and Run Android App
        run: npm run android &
        working-directory: my-app # Ensure it's running inside the correct directory

      - name: Install Maestro
        run: |
          export MAESTRO_VERSION=1.39.9
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
        working-directory: my-app

      - name: Start Screen Recording
        run: adb shell screenrecord /sdcard/maestro-test-video.mp4 &

      - name: Run Maestro Tests
        run: maestro test maestro/test.yaml
        working-directory: my-app

      - name: Stop Recording & Pull Video
        run: |
          adb shell killall -INT screenrecord || true
          adb pull /sdcard/maestro-test-video.mp4 maestro-test-video.mp4
        working-directory: my-app

      - name: Upload Test Video
        uses: actions/upload-artifact@v4
        with:
          name: maestro-test-video
          path: my-app/maestro-test-video.mp4
