name: React Native Expo CI with Maestro (Android)

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: macos-latest # MacOS is required for Android Emulator

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install Dependencies
        run: npm install

      - name: Start Android Emulator (Pixel 7, API 35)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          profile: pixel_7
          disable-animations: true
          script: echo "Android Emulator started!"

      - name: Print Emulator Details
        run: adb devices -l

      - name: Build and Run Android App
        run: npm run android & # Run in background to keep it running

      - name: Install Maestro
        run: |
          export MAESTRO_VERSION=1.39.9
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Start Screen Recording
        run: adb shell screenrecord /sdcard/maestro-test-video.mp4 &

      - name: Run Maestro Tests
        run: maestro test maestro/test.yaml

      - name: Stop Recording & Pull Video
        run: |
          adb shell killall -INT screenrecord || true
          adb pull /sdcard/maestro-test-video.mp4 maestro-test-video.mp4

      - name: Upload Test Video
        uses: actions/upload-artifact@v4
        with:
          name: maestro-test-video
          path: maestro-test-video.mp4
