name: React Native Expo CI with Maestro (Android)

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: macos-latest  # macOS is required for running Android Emulators

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo CLI
        run: npm install -g expo-cli
        working-directory: my-app

      - name: Install Dependencies
        run: npm install
        working-directory: my-app

      - name: Start Android Emulator (Pixel 3a, API 30)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis_playstore
          arch: x86_64
          profile: pixel_3a
          disable-animations: true
          emulator-options: "-no-boot-anim -no-window -gpu swiftshader_indirect"
          timeout-minutes: 15

      - name: Wait for Emulator to Boot
        run: |
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 5; done'
          echo "Emulator is fully booted!"

      - name: Print Emulator Details
        run: adb devices -l

      - name: Build and Run Android App
        run: npm run android &
        working-directory: my-app

      - name: Install Maestro
        run: |
          export MAESTRO_VERSION=1.39.9
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
        working-directory: my-app

      - name: Start Screen Recording
        run: adb shell screenrecord /sdcard/maestro-test-video.mp4 &
      
      - name: Run Maestro Tests
        run: maestro test maestro/test.yaml
        working-directory: my-app

      - name: Stop Recording & Pull Video
        run: |
          adb shell killall -INT screenrecord || true
          adb pull /sdcard/maestro-test-video.mp4 maestro-test-video.mp4
        working-directory: my-app

      - name: Upload Test Video
        uses: actions/upload-artifact@v4
        with:
          name: maestro-test-video
          path: my-app/maestro-test-video.mp4
